ownerid = "enter the owner id here"
prefix = "s!"
version = "1.0"
enviorement = "production"
[colors]
main = "4fc1e9"
error = "fd6868"
[emojis]
success = "✅"
error = "❌"
[logging]
guildjoin = true
guildleave = true
system = true
username = "Webhook Username"
avatar = "Link to image used as the webhook avatar"
[httpserver]
enabled = true
port = 3000
[cooldowns]
owner = 0
default = 3