ownerid = "enter the owner id here"
prefix = "s!"
version = "1.0"
[colors]
main = "2ECC71"
error = "fd6868"
[emojis]
success = "✅"
error = "❌"
[logging]
guildjoin = true
guildleave = true
system = true
username = "Seashell Nightly"
avatar = "https://cdn.discordapp.com/avatars/755911044177854586/6e8984122a4c0aa64e4890c874de63c5.webp"
[httpserver]
enabled = true
port = 3000
[cooldowns]
owner = 0
default = 3