name: Prettier 
on:
  # Run the workflow on a push to the nightly branch
  push:
    branches:
      - nightly
   # Run the workflow on a pull request to the main branch
  pull_request:
    branches:
     - main
   # Run the workflow daily
  schedule:
    - cron: '0 0 * * *'
jobs:
  prettier:
    if: ${{ contains(github.event.head_commit.message, 'prettify') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write --no-bracket-spacing **/*.{js,md}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
